### ISSUE TITLE
Introductory text to treatments

### ISSUE THREAD

**Issue by bixiou** [bixiou/oecd_climate#3]
For the moment, the text introducing the videos is just: "Please carefully watch this video until the end." because the video starts as soon as the respondent is on the page, so we don't want to distract them with long text. In Understanding economics survey, there is:
"Recent academic research has studied what the effects of income taxation/the federal estate tax are.
We will now show you one short video that summarizes some key ideas of these studies. Please pay
attention to the information provided as you will be asked questions about it later. Do not skip forward
or close the page while the video is running.
Please proceed to the next page when you are ready. Not that you will not be able to move forward
with the survey before the end of the short video."
Was this on a separate page, prior to the videos? Should we keep the short text or use the long one in a separate block?

**Comment by TobiasKruse** [comment]
Because we had a share of respondents go through the video too quickly, I think that adding the longer explanation for the 2nd pilot would be very useful. Perhaps it makes more people watch the entire treatment. That would be good to know prior to launching the full survey.

**Comment by bixiou** [comment]
Done.
