### ISSUE TITLE
Reword the open questions

### ISSUE THREAD

**Issue by bixiou** [bixiou/oecd_climate#4]
The three open questions are:
politics_field: "What are your political views? What political proposals do you support?"
CC_field: "What do you know about climate change? What are your views on climate change?"
policies_field: "Do you think the US government should fight climate change? If yes, how?"

To politics_field, only a few people actually give proposals and most answer something like "conservative" or "liberal".
To CC_field, people usually focus on the second question and answer things like "it's real, we should take action" or "fake news", but they don't answer the first one.
To policies_field, people answer succinctly but as expected.

To get more detailed responses, I suggest we drop the question allowing an easy answer in the first two open fields, rewording them into:
politics_field: "What political proposals do you support?"
CC_field: "What do you know about climate change?"

**Comment by TobiasKruse** [comment]
TK: Yes, sure. That sounds good. Are we getting additional useful information out of this though? I am not quite sure what additional information we learn from this that will be useful for the analysis. I could potentially give us some interesting anecdotal insight on policies or political views that are not explicitly covered in the survey, which we can mention. I think the open ended are useful for the pilot to see if we missed anything obvious. I am less clear on the purpose for the final survey. But I am fine to keep the question.

**Comment by bixiou** [comment]
I'd like to do some analysis based on the open fields, so it's important in my opinion. It's what best represents how people really think about these issues.

**Comment by bixiou** [comment]
Done.
