### ISSUE TITLE
New 'Welcome' page with OECD/Harvard Data Protection Notice

### ISSUE THREAD

**Issue by TobiasKruse** [bixiou/oecd_climate#5]
We have merged the Data Protection Notice that OECD requires with the Data Protection Information from the previous pilot that contains the contact details to Harvard University. This Notice is now approved by the OECD Data Protection Officer and should replace the current 'Welcome' page of the survey (document uploaded below).

**Comment by TobiasKruse** [comment]
[Personal Data Processing Form OECD Harvard Climate Project.docx](https://github.com/bixiou/oecd_climate/files/5917118/Personal.Data.Processing.Form.OECD.Harvard.Climate.Project.docx)

**Comment by bixiou** [comment]
Sure. Can you change the welcome page accordingly in the _non_ pilot survey and close this issue?

**Comment by TobiasKruse** [comment]
Done.
